#!/bin/bash

#===========================================================================
#	FILE: script_tp1
#	AUTHOR: Arthur BOUDREAULT
#	DESCRIPTION: réalisation du TP1 scripting bash xavki
#===========================================================================
